version: 2
jobs:
  build_amd64:
    working_directory: ~/docker-prometheus
    machine: true
    steps:
      - checkout
      - run: make ARCHITECTURES=amd64
      - run: make ARCHITECTURES=amd64 push
  build_i386:
    working_directory: ~/docker-prometheus
    machine: true
    steps:
      - checkout
      - run: make ARCHITECTURES=i386
      - run: make ARCHITECTURES=i386 push
  build_arm32v6:
    working_directory: ~/docker-prometheus
    machine: true
    steps:
      - checkout
      - run: make ARCHITECTURES=arm32v6
      - run: make ARCHITECTURES=arm32v6 push
  build_arm64v8:
    working_directory: ~/docker-prometheus
    machine: true
    steps:
      - checkout
      - run: make ARCHITECTURES=arm64v8
      - run: make ARCHITECTURES=arm64v8 push
  manifest:
    machine: true
    steps:
      - checkout
      - run: make manifest
  badge:
    machine: true
    steps:
      - run: curl -X POST https://hooks.microbadger.com/images/unibaktr/prometheus/e9fGgQrVSFA65atALdpeFUmGr0Y=

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build_amd64:
          filters:
            tags:
              only: /.*/
      - build_i386:
          filters:
            tags:
              only: /.*/
      - build_arm32v6:
          filters:
            tags:
              only: /.*/
      - build_arm64v8:
          filters:
            tags:
              only: /.*/
      - manifest:
          requires:
            - build_amd64
            - build_i386
            - build_arm32v6
            - build_arm64v8
          filters:
            tags:
              only: /.*/
      - badge:
         requires:
           - manifest
         filters:
           tags:
             only: /.*/
